import type { Metadata } from "next";
import Link from 'next/link'
import { Inter } from "next/font/google";
import { links } from "./styles.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Payment-Demo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={links}>
          <Link href="/">Home</Link>
          <Link href="/list">List</Link>
          <Link href="/clients">Clients</Link>
          <Link href="/tenants">Tenants</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
